#!/usr/bin/bash5
#
# Origin: GL.iNet firmware mt6000-4.11.0_beta1 (GL-MT6000).
# Modified: section_iface_is_up() gains a default-route fallback so a
# device with no netifd network.interface (GL cellular rmnet_dataN) can
# start. See patches/ for the diff against the unmodified original.
# Licence: GPL-2.0, derived from cake-autorate's launcher.sh.template.

umask 077
mkdir -p "/tmp/cake-autorate"
chmod 700 "/tmp/cake-autorate" 2>/dev/null || true

valid_config_keys=()
mapfile -t valid_config_keys < <(
	grep -E '^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*=' "/usr/lib/cake-autorate/defaults.sh" |
		sed -E 's/^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*).*/\1/'
)

is_valid_config_key()
{
	local key="$1"
	local valid_key

	for valid_key in "${valid_config_keys[@]}"
	do
		[[ "$key" == "$valid_key" ]] && return 0
	done

	return 1
}

emit_scalar_config()
{
	local key="$1"
	local value="$2"

	case "$key" in
		dl_owd_delta_delay_thr_ms|ul_owd_delta_delay_thr_ms|reflector_ping_interval_s)
			[[ "$value" =~ ^[0-9]+$ ]] && value="${value}.0"
			;;
	esac

	printf '%s=%q\n' "$key" "$value"
}

emit_reflectors_config()
{
	local value="$1"
	local reflectors=()
	local reflector
	local first=1

	value="${value//,/ }"
	read -r -a reflectors <<< "$value"

	printf 'reflectors=('
	for reflector in "${reflectors[@]}"
	do
		[[ -n "$reflector" ]] || continue
		[[ "$first" == "1" ]] || printf ' '
		printf '%q' "$reflector"
		first=0
	done
	printf ')\n'
}

ubus_iface_exists()
{
	local iface="$1"

	[[ -n "$iface" ]] || return 1
	ubus list 2>/dev/null | grep -Fqx "network.interface.${iface}"
}

is_ipv6_network_iface()
{
	local iface="$1"
	local proto

	[[ -n "$iface" ]] || return 1
	case "$iface" in
		*6) return 0 ;;
	esac

	proto="$(uci -q get "network.${iface}.proto")"
	case "$proto" in
		dhcpv6|6in4|6rd|dslite|map|464xlat) return 0 ;;
	esac

	return 1
}

network_iface_is_up()
{
	local iface="$1"

	ubus_iface_exists "$iface" || return 1
	is_ipv6_network_iface "$iface" && return 1
	[[ "$(ubus call "network.interface.${iface}" status 2>/dev/null | jsonfilter -e '@.up')" == "true" ]]
}

resolve_section_iface()
{
	local section="$1"
	local ul_if
	local item
	local status
	local device
	local l3_device

	case "$section" in
		*6) return 1 ;;
	esac

	ul_if="$(uci -q get "cake-autorate.${section}.ul_if")"
	if ubus_iface_exists "$ul_if"
	then
		is_ipv6_network_iface "$ul_if" && return 1
		printf '%s' "$ul_if"
		return 0
	fi

	for item in $(ubus list 2>/dev/null | sed -n 's/^network\.interface\.//p')
	do
		[[ "$item" == "loopback" ]] && continue
		is_ipv6_network_iface "$item" && continue
		status="$(ubus call "network.interface.${item}" status 2>/dev/null)"
		device="$(printf '%s' "$status" | jsonfilter -q -e '@.device')"
		l3_device="$(printf '%s' "$status" | jsonfilter -q -e '@.l3_device')"
		if [[ "$device" == "$ul_if" || "$l3_device" == "$ul_if" ]]
		then
			printf '%s' "$item"
			return 0
		fi
	done

	return 1
}

section_iface_is_up()
{
	local section="$1"
	local iface
	local ul_if

	iface="$(resolve_section_iface "$section")"
	network_iface_is_up "$iface" && return 0

	# Fallback: the device carries the default route but has no netifd
	# network.interface. GL cellular modems (rmnet_dataN) are exactly this.
	ul_if="$(uci -q get cake-autorate.${section}.ul_if)"
	[ -n "$ul_if" ] || return 1
	[ -e "/sys/class/net/${ul_if}" ] || return 1
	ip route show default dev "$ul_if" 2>/dev/null | grep -q . && return 0
	# Bridge-shaping mode: the shaped device is the LAN bridge or its IFB, so
	# it will never carry a default route. Require only that some WAN is up.
	case "$ul_if" in
		ifb4*|br-*) ip route show default 2>/dev/null | grep -q . && return 0 ;;
	esac
	return 1
}

generate_instance_config()
{
	local section="$1"
	local config_file="/tmp/cake-autorate/config.${section}.sh"
	local tmp_file="${config_file}.tmp"
	local key
	local value

	printf '%s\n' "# This file is automatically generated. Do not edit!" > "$tmp_file"
	printf '%s\n\n' "# You can edit the UCI configuration file /etc/config/cake-autorate." >> "$tmp_file"

	while IFS= read -r key
	do
		[[ "$key" == "enabled" ]] && continue
		is_valid_config_key "$key" || continue

		if value="$(uci -q get "cake-autorate.${section}.${key}")"
		then
			if [[ "$key" == "reflectors" ]]
			then
				emit_reflectors_config "$value" >> "$tmp_file"
			else
				emit_scalar_config "$key" "$value" >> "$tmp_file"
			fi
		fi
	done < <(
		uci -q show "cake-autorate.${section}" |
			sed -n -E "s/^cake-autorate\.${section}\.([A-Za-z_][A-Za-z0-9_]*)=.*/\1/p"
	)

	mv "$tmp_file" "$config_file"
}

cake_instances=()
if command -v uci >/dev/null 2>&1 && uci show cake-autorate >/dev/null 2>&1
then
	cake_uci_sections=$(uci show cake-autorate | awk -F'[.=]' '$1 == "cake-autorate" && $3 == "cake_autorate" { print $2 }')
	for cake_uci_section in ${cake_uci_sections}
	do
		[[ "$cake_uci_section" =~ ^[A-Za-z0-9_]+$ ]] || continue

		enabled=$(uci -q get "cake-autorate.${cake_uci_section}.enabled")
		[[ "${enabled}" != "1" ]] && continue # Skip disabled instances
		section_iface_is_up "$cake_uci_section" || continue # Skip instances whose source interface is down

		generate_instance_config "$cake_uci_section"
		cake_instances+=("/tmp/cake-autorate/config.${cake_uci_section}.sh")
	done
else
	cake_instances=(/tmp/cake-autorate/config.*.sh)
fi
cake_instance_pids=()

trap kill_cake_instances INT TERM EXIT

kill_cake_instances()
{
	trap - INT TERM EXIT

	echo "Killing all instances of cake one-by-one now."

	for ((cake_instance=0; cake_instance<${#cake_instances[@]}; cake_instance++))
	do
		kill "${cake_instance_pids[${cake_instance}]}" 2>/dev/null || true
	done
	wait
}

for cake_instance in "${cake_instances[@]}"
do
	/usr/lib/cake-autorate/cake-autorate.sh "${cake_instance}" &
	cake_instance_pids+=(${!})
done
wait
